### ISSUE TITLE
Replace Slack links with Discord links

### ISSUE THREAD

**Issue by avikalpg** [vibinex/vibinex-server#387]
We have created our [Vibinex Discord Community](https://discord.gg/sNbpJkEB).
And the Slack invitation link no longer works on the website.

Replace the Slack invitation links on the website with Discord invitation links. Also change the associated text, icons and file names.

Components:
1. `JoinSlack.tsx`
2. `Footer.tsx`

**Comment by SeanAverS** [comment]
Hello, 

I am interested on working on this. Could I please be assigned? Thank you.

**Comment by iaayushmaan** [comment]
Hey, the above discord invite link seems to be invalid.
